### ISSUE TITLE
pricing issue when quantities are used

### ISSUE THREAD

**Issue by gotyou** [somewherewarm/woocommerce-product-bundles-bulk-discounts#2]
Hello,

There is an issue when the bundle product option has a quantity enabled,  When 3|100 is used (first three free), if any of the options quantity is set to more than 1, it multiplies the price by the quantity, ignoring the rule.

Mark

**Comment by manospsyx** [comment]
@gotyou I think you might be misunderstanding how bulk discounts work?

`3|100` does not mean "first three free" -- it rather means that "if you purchase 3 items, you get a 100% discount".

`1-3|100` would mean that "if you purchase UP TO 3 items, you get a 100% discount".

Also discount rules are not calculated on top of each other. Only 1 discount is applied to the entire collection, based on the overall quantity of bundled items.

**Comment by gotyou** [comment]
Hello,

Hi di do not explain my self, so have set up a test link

https://missionready.co.uk/product/bundle-test/

this is set at a discount of 0-3|100

each of the products is set a quantity min 0 max 2 at £1.00 each
select three different products with a qty of 1, bundle total is £0.00. good
select four different products with a qty of 1, bundle total is £1.00. good
select 2 different products with a qty of 1, and one product to quantity 2 (4 in total), bundle total is £2.00, it should still be £1.00

Thanks

Mark

**Comment by jimjasson** [comment]
@franticpsyx I managed to replicate this locally. Here's the configuration I used: 
<img width="800" alt="edit product wc32 wordpress 2017-12-18 13-35-18" src="https://user-images.githubusercontent.com/25955483/34104301-8d2e3f3a-e3f8-11e7-8014-ee953934ab40.png">

In the single product page, try adding first the two optional bundled items with Min/Max quantity 1 and then the optional bundled item with Min/Max quantity 2.

**Comment by gotyou** [comment]
thanks, Mark

**Comment by manospsyx** [comment]
Thanks @jimjasson -- reopening!

**Comment by gotyou** [comment]
Found a workaround. no longer needed,

**Comment by manospsyx** [comment]
> select 2 different products with a qty of 1, and one product to quantity 2 (4 in total), bundle total is £2.00, it should still be £1.00

With these rules, 4 products in total should be 4 x £1.00 = £4.00

There is an issue when increasing the total quantity of items but the discount drops to zero which is unrelated to how @gotyou expects the plugin to work:

@gotyou I think you need to specify a new discount when the quantity of items is 4+, e.g. `4 | 75`, `5 | 60` and so on.
