### ISSUE TITLE
Items with a quantity that are not selected count towards the bundle discount

### ISSUE THREAD

**Issue by leonclaus** [somewherewarm/woocommerce-product-bundles-bulk-discounts#22]
**Observed behavior**

If you use the `WC_PB()->cart->add_bundle_to_cart()` function and pass a configuration array that contains items similar to this:

```php
[
    /* ...more item data... */
    'quantity' => 1,
    'optional_selected' => false,
]
```

Assuming that this item is optional, the bundled item in the cart will still count towards the bulk discount even though it is not actually added to the cart (because its optional and not selected). This means that the customer would get a discount he or she is not qualified for.

**Expected behavior**

The expected behavior might be one of the two:
1. Only count quantity if optional_selected is true (my preferred variant)
2. Throw an error when validating a configuration array that contains an item that is not selected, but has a quantity > 0. This, however, would probably require modifications to the documentation as well and makes development more difficult.

**Potential sources of error**

I found the following code:
https://github.com/somewherewarm/woocommerce-product-bundles-bulk-discounts/blob/43b491f27b857a489c9c2af636a9d3b49f8dd1f0/product-bundles-bulk-discounts-for-woocommerce.php#L476

Here, it should probably also be checked whether optional_selected is true instead of blindly adding all stamps to the cart.

**Comment by manospsyx** [comment]
@jimjasson can you take a look at this and (1) confirm the issue, (2) validate the PR?

**Comment by manospsyx** [comment]
@leonclaus thanks so much for reporting this 👍

**Comment by jimjasson** [comment]
@leonclaus Thanks again for bringing this up! 

@franticpsyx Confirmed that there is an issue on our side. 

I created a Product Bundle with two Simple Products -- one mandatory and one optional. I also set up a Bulk Discount rule like this: https://a.cl.ly/04uAp7k7.

Then, I ran this snippet: 

```
add_action( 'woocommerce_before_single_product', 'sw_pb_add_bundle_to_the_cart' );

function sw_pb_add_bundle_to_the_cart() {
	$args = array(
	    1801 => array(
	        'product_id' => 30,
	        'quantity' => 1,
	    ),
	    1805 => array(
	        'product_id' => 39,
	        'quantity' => 1,
	        'optional_selected' => 'no',
	    )
	);

	$added = WC_PB()->cart->add_bundle_to_cart( 57, 1, $args );
}
```

and indeed noticed that the Bulk Discount rules applied even though the second product was not added to the cart: https://a.cl.ly/eDujGmjm. 

Regarding the fix, I am not 100% sure that this is the best approach. I see that in Product Bundles, we automatically set the bundled item quantity to 0 if ` 'optional_selected' => 'no'`: https://a.cl.ly/ApuY57J7. 

Ref: https://github.com/somewherewarm/woocommerce-product-bundles/blob/c3b4576c4e3fcea9369df44163d1a11ab829b740/includes/class-wc-pb-cart.php#L311. 

Is there any way we can re-use `get_posted_bundle_configuration` in Bulk Discounts?

**Comment by leonclaus** [comment]
@jimjasson That approach would work as well and thats precisely how I handled it temporarily. Maybe the problem then is that this is only done on POSTed data and not on data passed to `WC_PB()->cart->add_bundle_to_cart()`?

**Comment by manospsyx** [comment]
> Regarding the fix, I am not 100% sure that this is the best approach

As far as I remember, `validate_bundle_configuration`, which is called from `add_bundle_to_cart`, would accept such a configuration as valid. 

Some possible solutions:

- Update `validate_bundle_configuration` to prevent such configs from being added to the cart (overkill).
- Modify `bundle_add_to_cart` to accept but modify such configs (not sure if modifying manually supplied data is a good idea, we should either accept or reject it).
- Take this edge case into consideration on the BD side of things (@leonclaus 's PR).

My vote goes with the last alternative, so I'd suggest we get #23 tweaked and merged :)

**Comment by jimjasson** [comment]
@franticpsyx Thank you for listing all the possible solutions for this one! 

I'd be happy to test https://github.com/somewherewarm/woocommerce-product-bundles-bulk-discounts/pull/23 once you and @leonclaus finish the code review! 🚀
